-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Profiles Table (Handles Privy Auth Users)
create table profiles (
  id text primary key, -- Privy DID (e.g. did:privy:...)
  role text check (role in ('requestor', 'supplier', 'admin', 'both')) not null,
  entity_type text check (entity_type in ('individual', 'company', 'institution', 'government', 'ngo')),
  nickname text,
  wallet_address text, -- Derived from embedded wallet or Metamask
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Projects Table
create table projects (
  id uuid default uuid_generate_v4() primary key,
  requestor_id text references profiles(id) not null,
  title text not null,
  description text,
  status text check (status in ('open', 'evaluating', 'awarded', 'closed')) default 'open',
  deadline timestamp with time zone not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Dynamic Criteria Table (One-to-Many with Projects)
create table project_criteria (
  id uuid default uuid_generate_v4() primary key,
  project_id uuid references projects(id) on delete cascade not null,
  name text not null, -- e.g., "Company Years of Experience", "Financial Capacity"
  description text,
  weight_percentage integer not null check (weight_percentage >= 0 and weight_percentage <= 100),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Bids Table
create table bids (
  id uuid default uuid_generate_v4() primary key,
  project_id uuid references projects(id) on delete cascade not null,
  supplier_id text references profiles(id) not null,
  anonymous_alias text not null, -- e.g., "Supplier-3F8A" (Blind Bidding feature)
  status text check (status in ('submitted', 'evaluated', 'won', 'lost')) default 'submitted',
  on_chain_hash text, -- Hash of the bid data submitted to smart contract
  ai_score numeric(5, 2), -- The score generated by the AI evaluation
  ai_reasoning text, -- The explanation for the score
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(project_id, supplier_id) -- A supplier can only bid once per project
);

-- 5. Bid Values Table (One-to-Many with Bids and Criteria)
create table bid_values (
  id uuid default uuid_generate_v4() primary key,
  bid_id uuid references bids(id) on delete cascade not null,
  criteria_id uuid references project_criteria(id) on delete cascade not null,
  value text not null, -- Supplier's answer/value for the criteria
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;
alter table projects enable row level security;
alter table project_criteria enable row level security;
alter table bids enable row level security;
alter table bid_values enable row level security;

-- Basic RLS Policies (Can be refined later)
create policy "Public projects are viewable by everyone" on projects for select using (true);
create policy "Public criteria are viewable by everyone" on project_criteria for select using (true);

-- Bids are only viewable by the supplier who made them, or the requestor of the project
create policy "Suppliers can view own bids" on bids for select using (auth.uid()::text = supplier_id);
create policy "Requestors can view bids for their projects" on bids for select using (
  exists (select 1 from projects where id = bids.project_id and requestor_id = auth.uid()::text)
);
